apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
  namespace: default 
spec:
  replicas: 5
  selectors:
   matchlabels:
    app: movie-app
templates:
   metadata
    labels
    app: movie-app
spec:
   containers:
    - name: movie-app
      image: sawaf007/
      ports: 
       - containerPort: 5000


